### ISSUE TITLE
propocisiones

### ISSUE THREAD

**Issue by NBbrook** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-NBbrook#1]
[INSTITUTO TECNOLOGICO DE TLAXIACO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-NBbrook/files/13197406/INSTITUTO.TECNOLOGICO.DE.TLAXIACO.pdf)

**Comment by 23620031** [comment]
PORTADA 25/25
PROCEDIMIENTO 25/25
FIGURAS 25/25
RESULTADO Y CONCLUCIÓN 17/25 (falta resultados)
_______________________________________________________________________________
CALIFICACIÓN TOTAL 18.4/20

CALIFICADO POR ISAÍAS Y EQUIPO

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
